---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  collections:
    - awx.awx
  vars:
    tower_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    tower_validate_certs: false

  tasks:
  - set_fact:
      environment_name_expanded: "Development"
    when: env == "Dev"

  - set_fact:
      environment_name_expanded: "QA"
    when: env == "QA"

  - set_fact:
      environment_name_expanded: "Production"
    when: env == "Prod"

  - name: Update inventory via source ==> EC2 Dynamic Source - "{{ content_view }}" "{{ environment_name_expanded }}"
    tower_inventory_source_update:
      name: "EC2 Dynamic Source - {{ content_view }} {{ environment_name_expanded }}"
      inventory: "{{ content_view }} {{ environment_name_expanded }}"
      organization: Default

  - name: Update inventory via source ==> inventory_{{ content_view | lower }}_{{ env | lower }}.aws_ec2
    tower_inventory_source_update:
      name: "inventory_{{ content_view | lower }}_{{ env | lower }}.aws_ec2"
      inventory: "ALL {{ environment_name_expanded }}"
      organization: Default
