---
- name: Format instance selection tags for ec2_remote_info
  ansible.builtin.command: python3 /usr/share/ansible/roles/ec2_node_tools/files/build_tags_dict.py "{{instances.tags}}"
  delegate_to: localhost
  connection: local
  register: ec2_remote_tags

- name: Get instance info
  amazon.aws.ec2_instance_info:
    filters: "{{ec2_remote_tags.stdout}}"
    region: "{{ ec2_region }}"
  delegate_to: localhost
  connection: local
  register: instances_details
