---
- name: "Ensure content view version is in all environments"
  redhat.satellite.content_view_version:
    username: "{{ username | default(omit) }}"
    password: "{{ password | default(omit) }}"
    server_url: "{{ server_url | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    content_view: "{{ item.content_view }}"
    organization: "{{ satellite_organization }}"
    version: "{{ item.content_view_update | d(false) | ternary(omit, 1.0) }}"
    lifecycle_environments: "{{ item.lifecycle_environments }}"
  async: "{{ publish_timeout }}"
  poll: 0
  register: publish_async

- name: Check if content view  is finished
  ansible.builtin.async_status:
    jid: "{{ publish_async.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: "{{ ( publish_timeout / publish_retry_interval ) | int }}"
  delay: "{{ publish_retry_interval }}"
