---
- block:

  - ansible.builtin.include_tasks: instance/stop_instances.yml

  - ansible.builtin.include_tasks: snapshot/snapshot_create.yml

  - ansible.builtin.include_tasks: instance/start_instances.yml

  delegate_to: localhost
